abcxyz/pmap

apis/v1alpha1/validation.go
apis/v1alpha1/validation_test.go
pkg/cli/mapping_validate_test.go
pkg/mapping/processors/assetinventory.go
pkg/mapping/processors/assetinventory_test.go
test/integration/main_test.go

Fix: Update annotation structure, put CAIS annotations under annotation["assetInfo"]

---

.github/workflows/fake-bets-mapping-snapshot-file-copy.yml
.github/workflows/fake-bets-policy-snapshot-file-change.yml

fix: fixed typo

---

.github/workflows/snapshot-file-change.yml

skip uploading when there is no changed yaml files

fix: skip uploading when there is no changed yaml files

---

.github/workflows/check.yml
.github/workflows/ci.yml
.github/workflows/snapshot-file-change.yml
.github/workflows/snapshot-file-copy.yml
.goreleaser.docker.yaml
.yamllint.yml
test/e2e/testdata/fakebets/mapping/product_team_a/product_x/x_mapping.yaml
test/e2e/testdata/fakebets/policy/product_team_b/product_y/y_policy.yaml

This will fail until https://github.com/abcxyz/pkg/pull/132 is merged.

Install yamllint

---

pkg/server/event_handler_test.go

Fix: update test to validate pmapEvent in successMessenger

---

.github/workflows/resource-mapping-check.yml

feat: make pmapctl version an input

---

.github/workflows/resource-mapping-check.yml

skip pmapctl check when there is no mapping change files

fix: skip pmapctl check when needed

---

.github/workflows/resource-mapping-check.yml
.github/workflows/snapshot-file-change.yml
test/integration/config.go

Update to pick up the fix of https://github.com/tj-actions/changed-files/issues/976

fix: update tj change action version

---

terraform/modules/pubsub-bigquery/main.tf

part of #118, 
Tested locally, this will create a DLQ for each bigquery subscription. 
TODO: update ci in infra to use this new module.

feat: add dlq for bigquery subscription

---

pkg/mapping/processors/assetinventory.go
test/integration/main_test.go

Fix: define user facing errors

---

terraform/ci/main.tf

Create a artifact registry repo as a static scoped non-GCS bucket resource in CI for integration test.

fix: create static scoped non-GCS bucket resource (AR repo) in CI for integration test

---

.github/workflows/ci.yml
terraform/e2e/variables.tf
terraform/modules/pmap-service/main.tf
terraform/modules/pmap-service/variables.tf
terraform/modules/pubsub-bigquery/main.tf

feat: added dlq pubsub for gcs push subscription

---

terraform/modules/pmap-service/main.tf
terraform/modules/pubsub-bigquery/main.tf

feat: enabled exponential backoff

---

.github/workflows/ci.yml
.github/workflows/fake-mapping-snapshot-file-change.yml
.github/workflows/fake-mapping-snapshot-file-copy.yml
.github/workflows/fake-policy-snapshot-file-change.yml
.github/workflows/fake-policy-snapshot-file-copy.yml
.github/workflows/release.yml
.github/workflows/resource-mapping-check.yml
.github/workflows/snapshot-file-change.yml
.github/workflows/snapshot-file-copy.yml

fix: added license header

---

pkg/server/config.go

fix: join errors in validation

---

docs/cli.md

feat: added pmap cli doc

---

test/integration/main_test.go

fix: add integration test case for subresource mapping

---

docs/prober-and-monitoring.md

feat: add prober readme

---

pkg/server/config.go

I think this would be helpful for users if they set the scope to folder level but didn't grant the service account the asset viewer role to the folder level.

chore: add some comments

---

terraform/e2e/main.tf
terraform/e2e/outputs.tf
terraform/modules/common/outputs.tf
terraform/modules/monitoring/alert.tf
terraform/modules/monitoring/variables.tf
terraform/modules/pubsub-bigquery/outputs.tf

feat: add alerting to e2e module

---

docs/release.md

docs: added release doc

---

terraform/ci/main.tf
terraform/modules/common/main.tf

It is missing some depndency which causes failure here https://github.com/abcxyz/infra/pull/446#issuecomment-1712077754

fix: fixed dependency

---

terraform/e2e/outputs.tf

added sa id output
Needed here: https://github.com/abcxyz/infra/blob/a4718c54f46e51f11ba137b401a859d8bfe850f5/terraform/deployment-resources/pmap-legacy/dev/main.tf#L38

feat: added sa id output

---

terraform/modules/monitoring/alert.tf
terraform/modules/monitoring/prober.tf

added missing dependency in prober

fix: added missing dependency

---

docs/release.md

fix: updated docs

---

terraform/e2e/outputs.tf

fix: added prober output in e2e

---

internal/testhelper/bq.go

This inlines the bqutil lookup. Previously we were reading every value only to pick the first entry.

Drop bqutil

---

.github/minty.yaml

Migration of configuration from: https://github.com/abcxyz/abcxyz-services/blob/main/github-token-minter/deployments/configs/abcxyz/pmap.yaml

feat: add minty configuration

---

.github/workflows/ci.yml
.github/workflows/release.yml
.github/workflows/resource-mapping-check.yml
.github/workflows/snapshot-file-change.yml
.github/workflows/snapshot-file-copy.yml
.github/workflows/update-ci-ar-cleanup-policy.yml
apis/v1alpha1/validation_test.go
pkg/cli/mapping_server_test.go
pkg/cli/mapping_validate_test.go
pkg/cli/policy_server_test.go
pkg/mapping/processors/assetinventory.go
pkg/mapping/processors/assetinventory_test.go
pkg/server/config_test.go
pkg/server/event_handler.go
pkg/server/event_handler_test.go
pkg/server/pubsub.go
pkg/server/pubsub_test.go
test/integration/main_test.go

This is no longer required as of Go 1.22+

Remove shadowed loop variables

---

.github/workflows/ci.yml
.github/workflows/release.yml
.github/workflows/resource-mapping-check.yml
.github/workflows/snapshot-file-change.yml
.github/workflows/update-ci-ar-cleanup-policy.yml

- Update workflow deps
- Replace vulnerable action per findings: https://www.stepsecurity.io/blog/harden-runner-detection-tj-actions-changed-files-action-is-compromised#recovery-steps

chore: update deps, replace tj-actions/changed-files
